FROM python:3.9-slim

WORKDIR /NEW FOLDER

RUN pip install -r requirements.txt

COPY . .

ENV LANGCHAIN_API_KEY=your-api-key-here
ENV LANGCHAIN_TRACING_V2=true

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
